import {
  Astrologer,
  NavLink,
  Pandit,
  PoojaService,
  Testimonial,
  TimeSlot,
} from './types';

export const poojaServices: PoojaService[] = [
  {
    id: 'griha-pravesh-puja',
    title: 'Griha Pravesh Puja',
    description: 'A traditional housewarming ceremony to bless your new home with peace and positive energy.',
    longDescription:
      'Griha Pravesh Puja marks the auspicious entry into a new home, invoking blessings for peace, prosperity, and protection for everyone who will live there. Our priests conduct the complete vidhi including Vastu Shanti, Navagraha pooja, and the sacred fire ceremony to purify the space before you move in.',
    price: '₹4,200',
    basePrice: 4200,
    duration: '3–5 hrs',
    rating: 4.9,
    reviews: 512,
    image: '/Griha-Pravesh-Puja.jpg',
    includes: ['Priest travel and setup', 'Havan samagri', 'Vastu Shanti rituals', 'Prasad for up to 20 guests'],
    packages: [
      { id: 'griha-pravesh-basic', name: 'Basic', price: 4200, features: ['1 priest', 'Core samagri kit', '3 hr ceremony'] },
      { id: 'griha-pravesh-standard', name: 'Standard', price: 5600, features: ['2 priests', 'Premium samagri kit', 'Prasad for 25 guests'] },
      { id: 'griha-pravesh-premium', name: 'Premium', price: 7400, features: ['2 priests', 'Premium samagri kit', 'Prasad for 40 guests', 'Full decor and flowers'] },
    ],
  },
  {
    id: 'vastu-shanti-puja',
    title: 'Vastu Shanti Puja',
    description: 'A remedial ritual to correct Vastu doshas and restore balance and harmony in your home or workplace.',
    longDescription:
      "Vastu Shanti Puja is performed to neutralize architectural and directional imperfections (Vastu doshas) in a home or workplace that may be causing stress, financial strain, or ill health. Our priests conduct havan and mantra chanting aligned to the nine directions, inviting the Vastu Purusha's blessings and restoring positive energy flow through the space.",
    price: '₹3,800',
    basePrice: 3800,
    duration: '2–3 hrs',
    rating: 4.8,
    reviews: 416,
    image: '/Griha-Pravesh-Puja.jpg',
    includes: ['Priest travel and setup', 'Havan samagri and kund', 'Ten-direction puja items', 'Prasad for up to 15 guests'],
    packages: [
      { id: 'vastu-shanti-basic', name: 'Basic', price: 3800, features: ['1 priest', 'Core samagri kit', '2 hr ceremony'] },
      { id: 'vastu-shanti-standard', name: 'Standard', price: 5200, features: ['1 priest', 'Premium samagri kit', 'Prasad for 15 guests', 'Vastu remedy consultation'] },
      { id: 'vastu-shanti-premium', name: 'Premium', price: 6800, features: ['2 priests', 'Premium samagri kit', 'Prasad for 25 guests', 'Decor and flowers included'] },
    ],
  },
  {
    id: 'naamkaran-sanskar',
    title: 'Naamkaran Sanskar (Naming Ceremony)',
    description: 'A joyous Vedic naming ceremony that welcomes your newborn into the family with blessings and a chosen name.',
    longDescription:
      "Naamkaran Sanskar is one of the sixteen sacred Hindu sanskaras, performed to formally name a newborn based on their birth nakshatra and rashi. Our priests calculate an auspicious muhurat and guide the family through the naming ritual, invoking blessings for the child's health, happiness, and a bright future.",
    price: '₹2,100',
    basePrice: 2100,
    duration: '1–2 hrs',
    rating: 4.9,
    reviews: 376,
    image: '/satyanarayan.jpeg',
    includes: ['Priest travel and setup', 'Naamkaran samagri', 'Nakshatra-based name suggestions', 'Printed vidhi guide'],
    packages: [
      { id: 'naamkaran-basic', name: 'Basic', price: 2100, features: ['1 priest', 'Core samagri kit', '1 hr ceremony'] },
      { id: 'naamkaran-standard', name: 'Standard', price: 2900, features: ['1 priest', 'Premium samagri kit', 'Personalized muhurat and name chart', 'Prasad for 15 guests'] },
      { id: 'naamkaran-premium', name: 'Premium', price: 3800, features: ['1 priest', 'Premium samagri kit', 'Prasad for 25 guests', 'Decor and flowers included'] },
    ],
  },
  {
    id: 'mundan-sanskar',
    title: 'Mundan Sanskar',
    description: "A traditional first haircut ceremony marking a child's purification and healthy growth.",
    longDescription:
      "Mundan Sanskar is performed to mark a child's first haircut, symbolizing the removal of past-life impurities and inviting blessings for healthy growth and long life. Our priests perform the sankalp and guide the ceremonial haircut with Vedic mantras, followed by a small havan for the child's wellbeing.",
    price: '₹1,900',
    basePrice: 1900,
    duration: '1–2 hrs',
    rating: 4.8,
    reviews: 298,
    image: '/satyanarayan.jpeg',
    includes: ['Priest travel and setup', 'Mundan samagri', 'Ceremonial haircut arrangement', 'Prasad for up to 15 guests'],
    packages: [
      { id: 'mundan-basic', name: 'Basic', price: 1900, features: ['1 priest', 'Core samagri kit', '1 hr ceremony'] },
      { id: 'mundan-standard', name: 'Standard', price: 2600, features: ['1 priest', 'Premium samagri kit', 'Small havan included', 'Prasad for 15 guests'] },
      { id: 'mundan-premium', name: 'Premium', price: 3400, features: ['1 priest', 'Premium samagri kit', 'Prasad for 25 guests', 'Decor and flowers included'] },
    ],
  },
  {
    id: 'annaprashan-sanskar',
    title: 'Annaprashan Sanskar',
    description: "A heartfelt ceremony celebrating your baby's first taste of solid food.",
    longDescription:
      "Annaprashan Sanskar celebrates a baby's first intake of solid food, traditionally performed in the sixth or eighth month. Our priests perform the sankalp and guide the family through the ritual feeding, invoking blessings for the child's health, nourishment, and prosperity.",
    price: '₹1,700',
    basePrice: 1700,
    duration: '1 hr',
    rating: 4.7,
    reviews: 214,
    image: '/satyanarayan.jpeg',
    includes: ['Priest travel and setup', 'Annaprashan samagri', 'Ceremonial feeding items', 'Prasad for up to 10 guests'],
    packages: [
      { id: 'annaprashan-basic', name: 'Basic', price: 1700, features: ['1 priest', 'Core samagri kit', '45 min ceremony'] },
      { id: 'annaprashan-standard', name: 'Standard', price: 2300, features: ['1 priest', 'Premium samagri kit', 'Keepsake photo assistance', 'Prasad for 15 guests'] },
      { id: 'annaprashan-premium', name: 'Premium', price: 3000, features: ['1 priest', 'Premium samagri kit', 'Prasad for 20 guests', 'Decor and flowers included'] },
    ],
  },
  {
    id: 'rudrabhishek',
    title: 'Rudrabhishek',
    description: 'A powerful Shiva abhishekam performed with Vedic mantras to remove obstacles and negativity.',
    longDescription:
      'Rudrabhishek is a potent abhishekam ceremony dedicated to Lord Shiva, invoking his Rudra form to dissolve obstacles, negativity, and long-standing hardships. The ritual involves chanting of the Rudra mantras while offering milk, honey, and sacred water over the Shiva lingam. It is especially recommended during Mahashivratri, Shravan month, or whenever a fresh start is needed.',
    price: '₹3,500',
    basePrice: 3500,
    duration: '3–4 hrs',
    rating: 4.9,
    reviews: 684,
    image: '/rudrabhishek.jpeg',
    includes: ['Priest travel and setup', 'Abhishekam samagri', 'Bilva leaves and flowers', 'Prasad for up to 15 guests'],
    packages: [
      { id: 'rudrabhishek-basic', name: 'Basic', price: 3500, features: ['1 priest', 'Core samagri kit', '3 hr ceremony'] },
      { id: 'rudrabhishek-standard', name: 'Standard', price: 4800, features: ['1 priest', 'Premium samagri kit', 'Rudraksha gift for host', 'Prasad for 20 guests'] },
      { id: 'rudrabhishek-premium', name: 'Premium', price: 6200, features: ['2 priests', 'Premium samagri kit', 'Prasad for 35 guests', 'Decor and flowers included'] },
    ],
  },
  {
    id: 'maha-mrityunjaya-havan',
    title: 'Maha Mrityunjaya Jaap / Havan',
    description: 'A powerful chant and fire ritual dedicated to Lord Shiva for health, protection, and longevity.',
    longDescription:
      'Maha Mrityunjaya Jaap invokes Lord Shiva through the powerful Mrityunjaya Mantra, believed to protect against illness, accidents, and untimely death while granting strength and longevity. Our priests perform the sankalp, chant the mantra in the prescribed count, and conclude with a havan offering ghee and sacred herbs into the sacred fire.',
    price: '₹4,500',
    basePrice: 4500,
    duration: '3–4 hrs',
    rating: 4.8,
    reviews: 356,
    image: '/rudrabhishek.jpeg',
    includes: ['Priest travel and setup', 'Havan samagri and kund', 'Mrityunjaya mantra jaap', 'Prasad for up to 15 guests'],
    packages: [
      { id: 'maha-mrityunjaya-basic', name: 'Basic', price: 4500, features: ['1 priest', '11,000 mantra jaap', '3 hr ceremony'] },
      { id: 'maha-mrityunjaya-standard', name: 'Standard', price: 6200, features: ['1 priest', '21,000 mantra jaap', 'Premium samagri kit', 'Prasad for 20 guests'] },
      { id: 'maha-mrityunjaya-premium', name: 'Premium', price: 8200, features: ['2 priests', '51,000 mantra jaap', 'Premium samagri kit', 'Prasad for 35 guests'] },
    ],
  },
  {
    id: 'durga-saptashati-havan',
    title: 'Durga Saptashati Path / Havan',
    description: 'A sacred recitation of the 700 verses of Durga Saptashati culminating in a havan for strength and protection.',
    longDescription:
      'Durga Saptashati Path involves the complete recitation of the 700 sacred verses glorifying Goddess Durga, invoking her protection, strength, and victory over obstacles. The path concludes with a havan where offerings are made to Agni, sealing the blessings invoked during the recitation.',
    price: '₹4,200',
    basePrice: 4200,
    duration: '3–4 hrs',
    rating: 4.9,
    reviews: 288,
    image: '/havan.jpg',
    includes: ['Priest travel and setup', 'Full Durga Saptashati path', 'Havan samagri and kund', 'Prasad for up to 15 guests'],
    packages: [
      { id: 'durga-saptashati-basic', name: 'Basic', price: 4200, features: ['1 priest', 'Full Saptashati path', '3 hr ceremony'] },
      { id: 'durga-saptashati-standard', name: 'Standard', price: 5800, features: ['2 priests', 'Full Saptashati path', 'Premium samagri kit', 'Prasad for 20 guests'] },
      { id: 'durga-saptashati-premium', name: 'Premium', price: 7600, features: ['3 priests', 'Full Saptashati path', 'Premium samagri kit', 'Prasad for 35 guests'] },
    ],
  },
  {
    id: 'hanuman-havan-sundarkand',
    title: 'Hanuman Havan / Sundarkand Path',
    description: "A devotional havan paired with the Sundarkand recitation to invoke Hanuman's strength and protection.",
    longDescription:
      "Hanuman Havan combined with Sundarkand Path invokes Lord Hanuman's blessings for courage, protection from negative energies, and the removal of obstacles. Our priests recite the Sundarkand chapter of the Ramcharitmanas followed by a havan, filling the home with devotion and positive energy.",
    price: '₹2,800',
    basePrice: 2800,
    duration: '2–3 hrs',
    rating: 4.8,
    reviews: 342,
    image: '/havan.jpg',
    includes: ['Priest travel and setup', 'Sundarkand path', 'Havan samagri and kund', 'Prasad for up to 15 guests'],
    packages: [
      { id: 'hanuman-havan-basic', name: 'Basic', price: 2800, features: ['1 priest', 'Sundarkand path', '2 hr ceremony'] },
      { id: 'hanuman-havan-standard', name: 'Standard', price: 3900, features: ['1 priest', 'Sundarkand path', 'Premium samagri kit', 'Prasad for 20 guests'] },
      { id: 'hanuman-havan-premium', name: 'Premium', price: 5100, features: ['2 priests', 'Sundarkand path', 'Premium samagri kit', 'Prasad for 35 guests'] },
    ],
  },
  {
    id: 'navagraha-puja',
    title: 'Navagraha Puja',
    description: 'A puja to balance the nine celestial bodies and reduce their unfavorable effects on your life.',
    longDescription:
      'Navagraha Puja pacifies the nine planetary deities — Surya, Chandra, Mangal, Budh, Guru, Shukra, Shani, Rahu, and Ketu — to reduce malefic planetary influences and strengthen favorable ones. Our priests perform individual offerings for each graha followed by a havan, recommended when a horoscope shows challenging planetary transits.',
    price: '₹3,200',
    basePrice: 3200,
    duration: '2–3 hrs',
    rating: 4.7,
    reviews: 265,
    image: '/havan.jpg',
    includes: ['Priest travel and setup', 'Navagraha samagri and kund', 'Individual offerings for all 9 grahas', 'Prasad for up to 15 guests'],
    packages: [
      { id: 'navagraha-basic', name: 'Basic', price: 3200, features: ['1 priest', 'Core samagri kit', '2 hr ceremony'] },
      { id: 'navagraha-standard', name: 'Standard', price: 4400, features: ['1 priest', 'Premium samagri kit', 'Personalized kundli review', 'Prasad for 20 guests'] },
      { id: 'navagraha-premium', name: 'Premium', price: 5800, features: ['2 priests', 'Premium samagri kit', 'Prasad for 35 guests', 'Decor and flowers included'] },
    ],
  },
  {
    id: 'kaal-sarp-dosh-puja',
    title: 'Kaal Sarp Dosh Puja',
    description: 'A remedial puja to reduce the effects of Kaal Sarp Dosh formed by Rahu-Ketu placement in your horoscope.',
    longDescription:
      'Kaal Sarp Dosh Puja is performed to ease the challenges associated with this planetary affliction, often linked to delays, anxiety, and obstacles in career or relationships. Our priests conduct the puja and havan dedicated to Rahu and Ketu, using authentic Vedic rites to restore balance and peace of mind.',
    price: '₹5,500',
    basePrice: 5500,
    duration: '3–4 hrs',
    rating: 4.8,
    reviews: 198,
    image: '/rudrabhishek.jpeg',
    includes: ['Priest travel and setup', 'Rahu-Ketu havan samagri', 'Naga (serpent) puja items', 'Prasad for up to 15 guests'],
    packages: [
      { id: 'kaal-sarp-basic', name: 'Basic', price: 5500, features: ['1 priest', 'Core samagri kit', '3 hr ceremony'] },
      { id: 'kaal-sarp-standard', name: 'Standard', price: 7600, features: ['1 priest', 'Premium samagri kit', 'Personalized dosh analysis', 'Prasad for 20 guests'] },
      { id: 'kaal-sarp-premium', name: 'Premium', price: 9900, features: ['2 priests', 'Premium samagri kit', 'Prasad for 35 guests', 'Decor and flowers included'] },
    ],
  },
  {
    id: 'mangal-dosh-puja',
    title: 'Mangal Dosh Puja',
    description: 'A remedial puja to pacify Mangal (Mars) dosha, commonly performed before marriage for a harmonious union.',
    longDescription:
      'Mangal Dosh Puja is performed to reduce the effects of an unfavorable Mars placement in the horoscope, often linked to delays or conflicts in marriage. Our priests conduct dedicated Mangal graha shanti rituals and a havan to pacify the planet and invoke a smooth, harmonious married life.',
    price: '₹3,400',
    basePrice: 3400,
    duration: '2–3 hrs',
    rating: 4.7,
    reviews: 231,
    image: '/havan.jpg',
    includes: ['Priest travel and setup', 'Mangal graha shanti samagri', 'Havan and kund', 'Prasad for up to 15 guests'],
    packages: [
      { id: 'mangal-dosh-basic', name: 'Basic', price: 3400, features: ['1 priest', 'Core samagri kit', '2 hr ceremony'] },
      { id: 'mangal-dosh-standard', name: 'Standard', price: 4700, features: ['1 priest', 'Premium samagri kit', 'Personalized kundli review', 'Prasad for 20 guests'] },
      { id: 'mangal-dosh-premium', name: 'Premium', price: 6100, features: ['2 priests', 'Premium samagri kit', 'Prasad for 30 guests', 'Decor and flowers included'] },
    ],
  },
  {
    id: 'shani-shanti-puja',
    title: 'Shani Shanti Puja',
    description: 'A puja to pacify Shani (Saturn) and ease the hardships of Sade Sati or Shani Dhaiya periods.',
    longDescription:
      'Shani Shanti Puja is performed to reduce the intensity of Saturn-related challenges, especially during Sade Sati or Shani Dhaiya transits. Our priests conduct Shani graha shanti rituals with oil offerings, mantra chanting, and a havan to invoke patience, discipline, and relief from prolonged hardships.',
    price: '₹3,600',
    basePrice: 3600,
    duration: '2–3 hrs',
    rating: 4.8,
    reviews: 276,
    image: '/havan.jpg',
    includes: ['Priest travel and setup', 'Shani graha shanti samagri', 'Til (sesame) oil offerings', 'Prasad for up to 15 guests'],
    packages: [
      { id: 'shani-shanti-basic', name: 'Basic', price: 3600, features: ['1 priest', 'Core samagri kit', '2 hr ceremony'] },
      { id: 'shani-shanti-standard', name: 'Standard', price: 5000, features: ['1 priest', 'Premium samagri kit', 'Personalized kundli review', 'Prasad for 20 guests'] },
      { id: 'shani-shanti-premium', name: 'Premium', price: 6500, features: ['2 priests', 'Premium samagri kit', 'Prasad for 30 guests', 'Decor and flowers included'] },
    ],
  },
  {
    id: 'lakshmi-ganesh-puja',
    title: 'Lakshmi-Ganesh Puja',
    description: 'A joint puja to Goddess Lakshmi and Lord Ganesha inviting wealth, prosperity, and new beginnings.',
    longDescription:
      'Lakshmi-Ganesh Puja combines worship of Goddess Lakshmi, the giver of wealth and abundance, with Lord Ganesha, the remover of obstacles. It is commonly performed at Diwali, business openings, and other auspicious occasions to invite prosperity and a smooth start to new ventures.',
    price: '₹2,200',
    basePrice: 2200,
    duration: '1–2 hrs',
    rating: 4.9,
    reviews: 402,
    image: '/ganeshpooja.jpeg',
    includes: ['Priest travel and setup', 'Lakshmi-Ganesh puja samagri', 'Modak and kheel-batasha prasad', 'Printed vidhi guide'],
    packages: [
      { id: 'lakshmi-ganesh-basic', name: 'Basic', price: 2200, features: ['1 priest', 'Core samagri kit', '1 hr ceremony'] },
      { id: 'lakshmi-ganesh-standard', name: 'Standard', price: 3000, features: ['1 priest', 'Premium samagri kit', 'Prasad for 15 guests'] },
      { id: 'lakshmi-ganesh-premium', name: 'Premium', price: 4000, features: ['1 priest', 'Premium samagri kit', 'Prasad for 25 guests', 'Decor included'] },
    ],
  },
  {
    id: 'navratri-kalash-sthapana',
    title: 'Navratri Kalash Sthapana & Durga Puja',
    description: 'A nine-day worship of Goddess Durga beginning with sacred Kalash Sthapana on the first day of Navratri.',
    longDescription:
      'Navratri Kalash Sthapana marks the start of the nine sacred nights dedicated to the nine forms of Goddess Durga. Our priests perform the ghatasthapana ritual on day one and conduct daily aarti and puja throughout Navratri, culminating in Kanya Pujan and a closing havan on Ashtami or Navami.',
    price: '₹6,500',
    basePrice: 6500,
    duration: '9 days (daily aarti)',
    rating: 4.9,
    reviews: 189,
    image: '/satyanarayan.jpeg',
    includes: ['Priest travel and setup', 'Kalash sthapana samagri', 'Daily aarti for 9 days', 'Kanya Pujan and closing havan'],
    packages: [
      { id: 'navratri-basic', name: 'Basic', price: 6500, features: ['1 priest', 'Kalash sthapana', 'Daily aarti (9 days)'] },
      { id: 'navratri-standard', name: 'Standard', price: 9000, features: ['1 priest', 'Kalash sthapana', 'Daily aarti (9 days)', 'Kanya Pujan on Ashtami'] },
      { id: 'navratri-premium', name: 'Premium', price: 11800, features: ['2 priests', 'Kalash sthapana', 'Daily aarti (9 days)', 'Kanya Pujan and closing havan', 'Decor and flowers included'] },
    ],
  },
  {
    id: 'ganesh-chaturthi-sthapana',
    title: 'Ganesh Chaturthi Sthapana & Visarjan',
    description: 'Full-service Ganpati sthapana, daily aarti, and visarjan for your home or community celebration.',
    longDescription:
      'Ganesh Chaturthi Sthapana & Visarjan covers the complete Ganpati festival journey — from the auspicious pranapratishtha (idol installation) to daily aarti and the closing visarjan ceremony. Our priests handle every ritual step so your celebration, whether 1.5 days or the full 11 days, stays authentic and stress-free.',
    price: '₹5,200',
    basePrice: 5200,
    duration: '1.5–11 days (sthapana to visarjan)',
    rating: 4.8,
    reviews: 246,
    image: '/ganeshpooja.jpeg',
    includes: ['Priest travel and setup', 'Sthapana (installation) puja', 'Daily aarti for chosen duration', 'Visarjan (immersion) ceremony'],
    packages: [
      { id: 'ganesh-chaturthi-basic', name: 'Basic', price: 5200, features: ['1 priest', 'Sthapana puja', 'Daily aarti (1.5 days)', 'Visarjan ceremony'] },
      { id: 'ganesh-chaturthi-standard', name: 'Standard', price: 7200, features: ['1 priest', 'Sthapana puja', 'Daily aarti (5 days)', 'Visarjan ceremony'] },
      { id: 'ganesh-chaturthi-premium', name: 'Premium', price: 9500, features: ['2 priests', 'Sthapana puja', 'Daily aarti (up to 11 days)', 'Visarjan ceremony', 'Decor and flowers included'] },
    ],
  },
  {
    id: 'karwa-chauth-puja',
    title: 'Karwa Chauth Puja',
    description: "A traditional puja guiding married women through the Karwa Chauth vrat rituals for their spouse's wellbeing.",
    longDescription:
      "Karwa Chauth Puja guides married women through the sacred vrat (fast) observed for their husband's long life and wellbeing. Our priests lead the katha narration, karwa (pot) puja, and moon-sighting ritual, helping families observe the tradition with complete authenticity.",
    price: '₹1,900',
    basePrice: 1900,
    duration: '1–2 hrs',
    rating: 4.9,
    reviews: 322,
    image: '/satyanarayan.jpeg',
    includes: ['Priest travel and setup', 'Karwa Chauth puja samagri', 'Katha narration', 'Printed vidhi guide'],
    packages: [
      { id: 'karwa-chauth-basic', name: 'Basic', price: 1900, features: ['1 priest', 'Core samagri kit', '1 hr ceremony'] },
      { id: 'karwa-chauth-standard', name: 'Standard', price: 2600, features: ['1 priest', 'Premium samagri kit', 'Group katha for up to 10 women'] },
      { id: 'karwa-chauth-premium', name: 'Premium', price: 3400, features: ['1 priest', 'Premium samagri kit', 'Group katha for up to 20 women', 'Decor included'] },
    ],
  },
  {
    id: 'satyanarayan-puja',
    title: 'Satyanarayan Puja (Festival/Occasion-based)',
    description: 'A sacred ritual invoking Lord Vishnu for prosperity, harmony, and the fulfillment of wishes on festivals or special occasions.',
    longDescription:
      'Satyanarayan Pooja is one of the most widely performed Vedic rituals, dedicated to Lord Vishnu in his form as Satyanarayan — the embodiment of truth. Traditionally performed on auspicious occasions, full moon days, or to mark new beginnings, this pooja brings prosperity, harmony, and the fulfillment of heartfelt wishes to your household. Our verified priests carry out every step exactly as prescribed in the scriptures, from the sankalp to the final aarti.',
    price: '₹2,100',
    basePrice: 2100,
    duration: '2–3 hrs',
    rating: 4.9,
    reviews: 458,
    image: '/satyanarayan.jpeg',
    includes: ['Priest travel and setup', 'All pooja samagri', 'Prasad for up to 15 guests', 'Printed vidhi guide'],
    packages: [
      { id: 'satyanarayan-basic', name: 'Basic', price: 2100, features: ['1 priest', 'Core samagri kit', '2 hr ceremony'] },
      { id: 'satyanarayan-standard', name: 'Standard', price: 3200, features: ['1 priest', 'Premium samagri kit', 'Prasad for 15 guests', 'Live video call for family'] },
      { id: 'satyanarayan-premium', name: 'Premium', price: 4600, features: ['2 priests', 'Premium samagri kit', 'Prasad for 30 guests', 'Decor and flowers included'] },
    ],
  },
  {
    id: 'ganesh-havan',
    title: 'Ganesh Havan',
    description: 'A fire ritual dedicated to Lord Ganesha to remove obstacles before starting new ventures or celebrations.',
    longDescription:
      'Ganesh Havan invokes Lord Ganesha through a dedicated fire ceremony, offering ghee, durva grass, and modaks into the sacred flame while chanting the Ganpati mantras. It is performed before major undertakings, festivals, or alongside other poojas to clear obstacles and invite auspicious beginnings.',
    price: '₹2,600',
    basePrice: 2600,
    duration: '2–3 hrs',
    rating: 4.8,
    reviews: 267,
    image: '/ganeshpooja.jpeg',
    includes: ['Priest travel and setup', 'Havan samagri and kund', 'Modak prasad', 'Printed vidhi guide'],
    packages: [
      { id: 'ganesh-havan-basic', name: 'Basic', price: 2600, features: ['1 priest', 'Core samagri kit', '2 hr ceremony'] },
      { id: 'ganesh-havan-standard', name: 'Standard', price: 3600, features: ['1 priest', 'Premium samagri kit', 'Prasad for 20 guests'] },
      { id: 'ganesh-havan-premium', name: 'Premium', price: 4700, features: ['2 priests', 'Premium samagri kit', 'Prasad for 30 guests', 'Decor included'] },
    ],
  },
  {
    id: 'gayatri-havan',
    title: 'Gayatri Havan',
    description: 'A Vedic fire ritual centered on the Gayatri Mantra for wisdom, clarity, and spiritual purification.',
    longDescription:
      'Gayatri Havan centers on the recitation of the revered Gayatri Mantra, invoking the divine light of knowledge and wisdom. Offerings of ghee and sacred herbs are made into the fire as the mantra is chanted in the prescribed count, purifying the surroundings and sharpening focus and clarity of mind.',
    price: '₹2,900',
    basePrice: 2900,
    duration: '2–3 hrs',
    rating: 4.7,
    reviews: 203,
    image: '/havan.jpg',
    includes: ['Priest travel and setup', 'Havan samagri and kund', 'Gayatri mantra jaap', 'Prasad for up to 15 guests'],
    packages: [
      { id: 'gayatri-havan-basic', name: 'Basic', price: 2900, features: ['1 priest', '11,000 mantra jaap', '2 hr ceremony'] },
      { id: 'gayatri-havan-standard', name: 'Standard', price: 4000, features: ['1 priest', '21,000 mantra jaap', 'Premium samagri kit', 'Prasad for 20 guests'] },
      { id: 'gayatri-havan-premium', name: 'Premium', price: 5200, features: ['2 priests', '51,000 mantra jaap', 'Premium samagri kit', 'Prasad for 30 guests'] },
    ],
  },
  {
    id: 'laghu-maha-rudra-havan',
    title: 'Laghu Rudra / Maha Rudra Havan',
    description: 'An elaborate multi-priest Rudra havan, performed at Laghu or Maha scale, for powerful Shiva blessings.',
    longDescription:
      'Laghu Rudra and Maha Rudra Havan are large-scale fire rituals built around repeated chanting of the Rudra Namakam and Chamakam, dedicated to Lord Shiva. Performed by a team of priests across multiple hours, this havan is reserved for major life events, temple consecrations, or when seeking powerful, large-scale blessings and obstacle removal.',
    price: '₹7,500',
    basePrice: 7500,
    duration: '4–6 hrs',
    rating: 4.9,
    reviews: 134,
    image: '/rudrabhishek.jpeg',
    includes: ['Priest travel and setup', 'Rudra havan samagri and kund', 'Rudra Namakam and Chamakam recitation', 'Prasad for up to 20 guests'],
    packages: [
      { id: 'rudra-havan-basic', name: 'Basic', price: 7500, features: ['3 priests', 'Laghu Rudra (11 rounds)', '4 hr ceremony'] },
      { id: 'rudra-havan-standard', name: 'Standard', price: 10200, features: ['5 priests', 'Laghu Rudra (11 rounds)', 'Premium samagri kit', 'Prasad for 30 guests'] },
      { id: 'rudra-havan-premium', name: 'Premium', price: 13500, features: ['11 priests', 'Maha Rudra (121 rounds)', 'Premium samagri kit', 'Prasad for 50 guests'] },
    ],
  },
  {
    id: 'purna-ahuti-havan',
    title: 'Purna Ahuti Havan',
    description: 'The grand closing fire offering that completes an extended havan or Vedic ritual sequence.',
    longDescription:
      'Purna Ahuti Havan is the final, grand offering that formally concludes an extended havan, yagna, or multi-day ritual sequence. Our priests perform the complete closing sequence — final ahutis, aarti, and blessings — sealing the sankalp and ensuring the full benefit of the preceding rituals is invoked.',
    price: '₹8,500',
    basePrice: 8500,
    duration: '4–6 hrs',
    rating: 4.8,
    reviews: 96,
    image: '/havan.jpg',
    includes: ['Priest travel and setup', 'Purna Ahuti samagri and kund', 'Closing aarti and blessings', 'Prasad for up to 25 guests'],
    packages: [
      { id: 'purna-ahuti-basic', name: 'Basic', price: 8500, features: ['2 priests', 'Core samagri kit', '4 hr ceremony'] },
      { id: 'purna-ahuti-standard', name: 'Standard', price: 11500, features: ['3 priests', 'Premium samagri kit', 'Prasad for 35 guests'] },
      { id: 'purna-ahuti-premium', name: 'Premium', price: 15000, features: ['5 priests', 'Premium samagri kit', 'Prasad for 50 guests', 'Decor and flowers included'] },
    ],
  },
];

export const navLinks: NavLink[] = [
  { label: 'Home', href: '/' },
  {
    label: 'Pooja',
    href: '/pooja',
    children: poojaServices.map((pooja) => ({ label: pooja.title, href: `/pooja/${pooja.id}` })),
  },
  {
    label: 'Astrology',
    href: '/astrology',
    children: [
      { label: 'Talk to Astrologer', href: '/astrology?mode=talk' },
      { label: 'Chat with Astrologer', href: '/astrology?mode=chat' },
    ],
  },
  { label: 'Why Namoh', href: '/#why-namoh' },
];

export const pandits: Pandit[] = [
  {
    id: 'pandit-suresh-mishra',
    name: 'Pandit Suresh Mishra',
    specialization: 'Vishnu and Satyanarayan Poojas',
    experience: '20 yrs experience',
    rating: 4.9,
    reviews: 980,
    languages: ['Hindi', 'Sanskrit', 'English'],
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=600&auto=format&fit=crop',
    fee: 1100,
  },
  {
    id: 'pandit-om-prakash',
    name: 'Pandit Om Prakash Sharma',
    specialization: 'Rudrabhishek and Shiva Rituals',
    experience: '17 yrs experience',
    rating: 4.8,
    reviews: 740,
    languages: ['Hindi', 'Sanskrit'],
    image: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?q=80&w=600&auto=format&fit=crop',
    fee: 1300,
  },
  {
    id: 'pandit-vinod-tripathi',
    name: 'Pandit Vinod Tripathi',
    specialization: 'Ganesh and Navagraha Poojas',
    experience: '14 yrs experience',
    rating: 4.7,
    reviews: 610,
    languages: ['Hindi', 'Marathi', 'English'],
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600&auto=format&fit=crop',
    fee: 950,
  },
  {
    id: 'pandit-harish-dwivedi',
    name: 'Pandit Harish Dwivedi',
    specialization: 'Griha Pravesh and Vastu Shanti',
    experience: '23 yrs experience',
    rating: 5.0,
    reviews: 1120,
    languages: ['Hindi', 'Sanskrit', 'English'],
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600&auto=format&fit=crop',
    fee: 1500,
  },
];

export const timeSlots: TimeSlot[] = [
  { id: 'slot-1', label: '06:00 AM – 07:00 AM', period: 'Morning' },
  { id: 'slot-2', label: '08:00 AM – 09:00 AM', period: 'Morning' },
  { id: 'slot-3', label: '10:00 AM – 11:00 AM', period: 'Morning' },
  { id: 'slot-4', label: '12:00 PM – 01:00 PM', period: 'Afternoon' },
  { id: 'slot-5', label: '02:00 PM – 03:00 PM', period: 'Afternoon' },
  { id: 'slot-6', label: '04:00 PM – 05:00 PM', period: 'Afternoon' },
  { id: 'slot-7', label: '06:00 PM – 07:00 PM', period: 'Evening' },
  { id: 'slot-8', label: '07:30 PM – 08:30 PM', period: 'Evening' },
];

export const astrologers: Astrologer[] = [
  {
    id: 'pandit-ram-shankar',
    name: 'Pandit Ram Shankar',
    specialty: 'Vedic Astrology',
    experience: '22 yrs experience',
    rating: 4.9,
    reviews: 1840,
    languages: ['Hindi', 'English', 'Sanskrit'],
    image: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'acharya-meera-devi',
    name: 'Acharya Meera Devi',
    specialty: 'Numerology & Tarot',
    experience: '15 yrs experience',
    rating: 4.8,
    reviews: 1120,
    languages: ['Hindi', 'English'],
    image: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'guru-anand-joshi',
    name: 'Guru Anand Joshi',
    specialty: 'Palmistry & Vastu',
    experience: '18 yrs experience',
    rating: 4.9,
    reviews: 2210,
    languages: ['Hindi', 'Marathi', 'English'],
    image: 'https://images.unsplash.com/photo-1568602471122-7832951cc4c5?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'jyotish-priya-sharma',
    name: 'Jyotish Priya Sharma',
    specialty: 'Kundli Matching',
    experience: '12 yrs experience',
    rating: 4.7,
    reviews: 860,
    languages: ['Hindi', 'English', 'Punjabi'],
    image: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=600&auto=format&fit=crop',
  },
  {
    id: 'pandit-devraj-tiwari',
    name: 'Pandit Devraj Tiwari',
    specialty: 'Horoscope & Muhurat',
    experience: '25 yrs experience',
    rating: 5.0,
    reviews: 3040,
    languages: ['Hindi', 'Sanskrit', 'English'],
    image: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=600&auto=format&fit=crop',
  },
];

export const testimonials: Testimonial[] = [
  {
    id: 't1',
    name: 'Anjali Mehta',
    location: 'Mumbai, India',
    quote:
      'The Griha Pravesh pooja was conducted with so much devotion and precision. Namoh made the entire process effortless and deeply meaningful for our family.',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?q=80&w=200&auto=format&fit=crop',
    rating: 5,
  },
  {
    id: 't2',
    name: 'Rohit Sharma',
    location: 'Delhi, India',
    quote:
      "Pandit Devraj's guidance on my career transit was remarkably accurate. The consultation felt personal, not transactional. Highly recommend Namoh.",
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop',
    rating: 5,
  },
  {
    id: 't3',
    name: 'Priya Nair',
    location: 'Bengaluru, India',
    quote:
      'From booking to the actual ceremony, everything felt authentic and well organized. The priest was punctual and incredibly knowledgeable.',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop',
    rating: 4,
  },
];
